### ISSUE TITLE
yam-allowlist-manager blocks access to irssi.org even though it's in my allow list

### ISSUE THREAD

**Issue by atsaloli** [sarangak/yam-allowlist-manager#3]
I've added `irssi.org` to my allow list but yam-allowlist-manager is not allowing it:

![screenshot](https://user-images.githubusercontent.com/508704/208782889-c8388d15-f5cc-43df-bfd3-f34b53dd814e.png)

![screenshot](https://user-images.githubusercontent.com/508704/208783002-5f546c33-953e-4229-a9ec-930bb162e51b.png)

**Comment by atsaloli** [comment]
This is happening now with other websites as well.

I have 444 entries in my allow list. Could I be hitting some kind of limit?  I can't add new entries to the allow list that actually work (allow access).

Where does yam-allowlist-manager store the allow list?  I tried to looking for it but couldn't find it.

**Comment by atsaloli** [comment]
My workaround is to disable the extension, which defeats the purpose of having the extension.

**Comment by sarangak** [comment]
Hi @atsaloli, thank you for giving it a try.  I finally had time to work on this last month and released a new version with #4 that makes significant changes to the extension as required by the new Manifest v3 framework mandated by Chrome.  I've also added some debugging statements to more easily debug issues like this in the future.

I'm guessing you have moved on, but if you or others continue to have issues, you can post them here and I can take a look.
